# country_constants.py

COUNTRY_MAP = {
    "AFG": ["Afghanistan", "Afghan"],
    "ALB": ["Albania", "Albanian"],
    "ALG": ["Algeria", "Algerian"],
    "AND": ["Andorra", "Andorran"],
    "ANG": ["Angola", "Angolan"],
    "ANT": ["Antigua", "Barbuda", "Antiguan"],
    "ARG": ["Argentina", "Argentine", "Argentinian"],
    "ARM": ["Armenia", "Armenian"],
    "ARU": ["Aruba", "Aruban"],
    "ASA": ["American Samoa", "Samoan"],
    "AUS": ["Australia", "Australian"],
    "AUT": ["Austria", "Austrian"],
    "AZE": ["Azerbaijan", "Azerbaijani", "Azeri"],
    "BAH": ["Bahamas", "Bahamian"],
    "BAN": ["Bangladesh", "Bangladeshi"],
    "BAR": ["Barbados", "Barbadian", "Bajan"],
    "BDI": ["Burundi", "Burundian"],
    "BEL": ["Belgium", "Belgian"],
    "BEN": ["Benin", "Beninese"],
    "BER": ["Bermuda", "Bermudian"],
    "BHU": ["Bhutan", "Bhutanese"],
    "BIH": ["Bosnia", "Herzegovina", "Bosnian"],
    "BIZ": ["Belize", "Belizean"],
    "BLR": ["Belarus", "Belarusian"],
    "BOL": ["Bolivia", "Bolivian"],
    "BOT": ["Botswana", "Motswana", "Botswanan"],
    "BRA": ["Brazil", "Brazilian"],
    "BRN": ["Bahrain", "Bahraini"],
    "BRU": ["Brunei", "Bruneian"],
    "BUL": ["Bulgaria", "Bulgarian"],
    "BUR": ["Burkina Faso", "Burkinabe"],
    "CAF": ["Central African Republic"],
    "CAM": ["Cambodia", "Cambodian"],
    "CAN": ["Canada", "Canadian"],
    "CAY": ["Cayman Islands", "Caymanian"],
    "CGO": ["Congo", "Congolese"],
    "CHA": ["Chad", "Chadian"],
    "CHI": ["Chile", "Chilean"],
    "CHN": ["China", "Chinese"],
    "CIV": ["Ivory Coast", "Cote d'Ivoire", "Ivorian"],
    "CMR": ["Cameroon", "Cameroonian"],
    "COD": ["DR Congo", "Democratic Republic of the Congo", "Congolese"],
    "COK": ["Cook Islands"],
    "COL": ["Colombia", "Colombian"],
    "COM": ["Comoros", "Comorian"],
    "CPV": ["Cape Verde", "Cape Verdean"],
    "CRC": ["Costa Rica", "Costa Rican"],
    "CRO": ["Croatia", "Croatian"],
    "CUB": ["Cuba", "Cuban"],
    "CYP": ["Cyprus", "Cypriot"],
    "CZE": ["Czech Republic", "Czechia", "Czech"],
    "DEN": ["Denmark", "Danish", "Dane"],
    "DJI": ["Djibouti", "Djiboutian"],
    "DMA": ["Dominica"],
    "DOM": ["Dominican Republic", "Dominican"],
    "ECU": ["Ecuador", "Ecuadorian"],
    "EGY": ["Egypt", "Egyptian"],
    "ERI": ["Eritrea", "Eritrean"],
    "ESA": ["El Salvador", "Salvadoran"],
    "ESP": ["Spain", "Spanish", "Spaniard"],
    "EST": ["Estonia", "Estonian"],
    "ETH": ["Ethiopia", "Ethiopian"],
    "FIJ": ["Fiji", "Fijian"],
    "FIN": ["Finland", "Finnish", "Finn"],
    "FRA": ["France", "French", "Frenchman"],
    "FSM": ["Micronesia"],
    "GAB": ["Gabon", "Gabonese"],
    "GAM": ["Gambia", "Gambian"],
    "GBR": ["United Kingdom", "Great Britain", "British", "UK", "GB", "English", "Scottish", "Welsh", "Northern Irish"],
    "GBS": ["Guinea-Bissau"],
    "GEO": ["Georgia", "Georgian"],
    "GEQ": ["Equatorial Guinea"],
    "GER": ["Germany", "German"],
    "GHA": ["Ghana", "Ghanaian"],
    "GRE": ["Greece", "Greek"],
    "GRN": ["Grenada", "Grenadian"],
    "GUA": ["Guatemala", "Guatemalan"],
    "GUI": ["Guinea", "Guinean"],
    "GUM": ["Guam"],
    "GUY": ["Guyana", "Guyanese"],
    "HAI": ["Haiti", "Haitian"],
    "HKG": ["Hong Kong"],
    "HON": ["Honduras", "Honduran"],
    "HUN": ["Hungary", "Hungarian"],
    "INA": ["Indonesia", "Indonesian"],
    "IND": ["India", "Indian"],
    "IRI": ["Iran", "Iranian"],
    "IRL": ["Ireland", "Irish"],
    "IRQ": ["Iraq", "Iraqi"],
    "ISL": ["Iceland", "Icelandic"],
    "ISR": ["Israel", "Israeli"],
    "ISV": ["Virgin Islands"],
    "ITA": ["Italy", "Italian"],
    "IVB": ["British Virgin Islands"],
    "JAM": ["Jamaica", "Jamaican"],
    "JOR": ["Jordan", "Jordanian"],
    "JPN": ["Japan", "Japanese"],
    "KAZ": ["Kazakhstan", "Kazakh", "Kazakhstani"],
    "KEN": ["Kenya", "Kenyan"],
    "KGZ": ["Kyrgyzstan", "Kyrgyz"],
    "KIR": ["Kiribati"],
    "KOR": ["South Korea", "Korean"],
    "KSA": ["Saudi Arabia", "Saudi"],
    "KUW": ["Kuwait", "Kuwaiti"],
    "LAO": ["Laos", "Laotian"],
    "LAT": ["Latvia", "Latvian"],
    "LBA": ["Libya", "Libyan"],
    "LBN": ["Lebanon", "Lebanese"],
    "LBR": ["Liberia", "Liberian"],
    "LCA": ["Saint Lucia", "Saint Lucian"],
    "LES": ["Lesotho"],
    "LIE": ["Liechtenstein"],
    "LTU": ["Lithuania", "Lithuanian"],
    "LUX": ["Luxembourg"],
    "MAD": ["Madagascar", "Malagasy"],
    "MAR": ["Morocco", "Moroccan"],
    "MAS": ["Malaysia", "Malaysian"],
    "MAW": ["Malawi", "Malawian"],
    "MDA": ["Moldova", "Moldovan"],
    "MDV": ["Maldives", "Maldivian"],
    "MEX": ["Mexico", "Mexican"],
    "MGL": ["Mongolia", "Mongolian"],
    "MHL": ["Marshall Islands"],
    "MKD": ["North Macedonia", "Macedonian"],
    "MLI": ["Mali", "Malian"],
    "MLT": ["Malta", "Maltese"],
    "MNE": ["Montenegro", "Montenegrin"],
    "MON": ["Monaco", "Monegasque"],
    "MOZ": ["Mozambique", "Mozambican"],
    "MRI": ["Mauritius", "Mauritian"],
    "MTN": ["Mauritania", "Mauritanian"],
    "MYA": ["Myanmar", "Burma", "Burmese"],
    "NAM": ["Namibia", "Namibian"],
    "NCA": ["Nicaragua", "Nicaraguan"],
    "NED": ["Netherlands", "Dutch"],
    "NEP": ["Nepal", "Nepalese"],
    "NGR": ["Nigeria", "Nigerian"],
    "NIG": ["Niger", "Nigerien"],
    "NOR": ["Norway", "Norwegian"],
    "NRU": ["Nauru"],
    "NZL": ["New Zealand", "New Zealander", "Kiwi"],
    "OMA": ["Oman", "Omani"],
    "PAK": ["Pakistan", "Pakistani"],
    "PAN": ["Panama", "Panamanian"],
    "PAR": ["Paraguay", "Paraguayan"],
    "PER": ["Peru", "Peruvian"],
    "PHI": ["Philippines", "Filipino"],
    "PLE": ["Palestine", "Palestinian"],
    "PLW": ["Palau"],
    "PNG": ["Papua New Guinea"],
    "POL": ["Poland", "Polish"],
    "POR": ["Portugal", "Portuguese"],
    "PRK": ["North Korea"],
    "PUR": ["Puerto Rico", "Puerto Rican"],
    "QAT": ["Qatar", "Qatari"],
    "ROU": ["Romania", "Romanian"],
    "RSA": ["South Africa", "South African"],
    "RUS": ["Russia", "Russian"], 
    "ANA": ["Authorised Neutral Athlete", "Russia", "Belarus"],
    "RWA": ["Rwanda", "Rwandan"],
    "SAM": ["Samoa", "Samoan"],
    "SEN": ["Senegal", "Senegalese"],
    "SEY": ["Seychelles", "Seychellois"],
    "SGP": ["Singapore", "Singaporean"],
    "SKN": ["Saint Kitts", "Nevis", "Kittitian"],
    "SLE": ["Sierra Leone", "Sierra Leonean"],
    "SLO": ["Slovenia", "Slovenian"],
    "SMR": ["San Marino", "Sammarinese"],
    "SOL": ["Solomon Islands"],
    "SOM": ["Somalia", "Somali"],
    "SRB": ["Serbia", "Serbian"],
    "SRI": ["Sri Lanka", "Sri Lankan"],
    "SSD": ["South Sudan", "South Sudanese"],
    "STP": ["Sao Tome", "Principe"],
    "SUD": ["Sudan", "Sudanese"],
    "SUI": ["Switzerland", "Swiss"],
    "SUR": ["Suriname", "Surinamese"],
    "SVK": ["Slovakia", "Slovak"],
    "SWE": ["Sweden", "Swedish", "Swede"],
    "SWZ": ["Eswatini", "Swaziland"],
    "SYR": ["Syria", "Syrian"],
    "TAN": ["Tanzania", "Tanzanian"],
    "TGA": ["Tonga", "Tongan"],
    "THA": ["Thailand", "Thai"],
    "TJK": ["Tajikistan", "Tajik"],
    "TKM": ["Turkmenistan", "Turkmen"],
    "TLS": ["Timor-Leste", "East Timor"],
    "TOG": ["Togo", "Togolese"],
    "TPE": ["Chinese Taipei", "Taiwan", "Taiwanese"],
    "TTO": ["Trinidad", "Tobago", "Trinidadian"],
    "TUN": ["Tunisia", "Tunisian"],
    "TUR": ["Turkey", "Turkish", "Turkiye"],
    "TUV": ["Tuvalu"],
    "UAE": ["United Arab Emirates", "Emirati"],
    "UGA": ["Uganda", "Ugandan"],
    "UKR": ["Ukraine", "Ukrainian"],
    "URU": ["Uruguay", "Uruguayan"],
    "USA": ["United States", "American", "USA", "U.S.", "US"],
    "UZB": ["Uzbekistan", "Uzbek"],
    "VAN": ["Vanuatu"],
    "VEN": ["Venezuela", "Venezuelan"],
    "VIE": ["Vietnam", "Vietnamese"],
    "VIN": ["Saint Vincent", "Grenadines"],
    "YEM": ["Yemen", "Yemeni"],
    "ZAM": ["Zambia", "Zambian"],
    "ZIM": ["Zimbabwe", "Zimbabwean"]
}